### PR TITLE
removed base path from dbd_url configuration

### PR DESCRIPTION
**Pull request by ploki**
removed base path from dbd_url configuration

### CODE REVIEW

**Comment by ttvi** [comment]
Maybe it's too late/early and maybe it's not related at all but what is the rationale of choosing the path-based approach thus restricting ourselves to not having (or may have with outrageous cost) `mv` and to very expensive `ls`?

**Comment by ploki** [comment]
it's because S3 protocol is path-based. We would have been able to use metadata/sproxyd to implement an inode based FSAL, but this approach implies to drop the compatibility with S3 connector which is the purpose of this development.

**Comment by ttvi** [comment]
To make it clear, what is the compatibility you are mentioning?
Maybe using the path-based approach with delimiter of S3 as a convenient way to build the hierarchical structure of the file system is a good way to start with, but it has so many limitations (including those mentioned before).
Perhaps we don't need to strictly use the delimiting function of S3. I saw some work having a flat table (like metadata) of `inode_number:child_entry` - `metadata` pairs. We can have the similar performance/style of the inode approach while still relying on S3 for providing the scalability of file system's directory (1 directory entry = 1 key---the same to path-based approach, listing directory = listing with prefix `inode_number`, etc).

_edit_: and most beautiful of all, moving a directory who has a deeply nested hierarchy is just a breeze of creating a new entry + removing the old entry.

**Comment by ploki** [comment]
I'm not quite sure to understand your point.

We want to see the same data from both S3 and NFS, and these visions must present the same hierarchical structure from both ends, without obfuscating data.

Going from bucket/prefix to inode representation implies compromises. As well as the other way. Since S3 is the first class citizen, compromises fall on NFS vision.

Maybe a lingua franca that permits an efficient implementation of both representations exists. But if it even exists, it behoves Metadata to offer both bucket/prefix and inode representations of the content based on it. And so, we should be able to switch to a more efficient inode representation for NFS.

**Comment by ttvi** [comment]
`"We want to see the same data from both S3 and NFS"`: ok I see, this is the compatibility point you're talking about.

**Comment by ThibaultRiviere** [comment]
:+1:

**Comment by ploki** [comment]
outdated by 7ade718fa2baabc77d8dd9b8180fcd050711c939

**Pull request closed without merging**
